datasets:
  log_1_layer_ann:
    column_mapping:
      categorical_features: [ 'sequence', 'variables', 'danger' ]
      numerical_features: [ ]
      datetime: 'timestamp'
      target: 'target'
      prediction: 'prediction'
    data_format:
      header: true
      separator: ','
      date_column: 'timestamp'
    monitors:
      - data_drift
      - classification_performance
      - cat_target_drift
  log_rf:
    column_mapping:
      categorical_features: [ 'sequence', 'variables', 'danger' ]
      numerical_features: [ ]
      datetime: 'timestamp'
      target: 'target'
      prediction: 'prediction'
    data_format:
      header: true
      separator: ','
      date_column: 'timestamp'
    monitors:
      - data_drift
      - classification_performance
      - cat_target_drift
  fetal_health_rf:
    column_mapping:
      categorical_features: [ 'fetal_health' ]
      numerical_features: 
        - 'baseline value'
        - 'accelerations'
        - 'fetal_movement'
        - 'uterine_contractions'
        - 'light_decelerations'
        - 'severe_decelerations'
        - 'prolongued_decelerations'
        - 'abnormal_short_term_variability'
        - 'mean_value_of_short_term_variability'
        - 'percentage_of_time_with_abnormal_long_term_variability'
        - 'mean_value_of_long_term_variability'
        - 'histogram_width'
        - 'histogram_min'
        - 'histogram_max'
        - 'histogram_number_of_peaks'
        - 'histogram_number_of_zeroes'
        - 'histogram_mode'
        - 'histogram_mean'
        - 'histogram_median'
        - 'histogram_variance'
        - 'histogram_tendency'
      prediction: 'prediction'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
      - classification_performance
      - num_target_drift
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
  source: s3
  bucket: datakflow
