datasets:
  log_1_layer_ann:
    column_mapping:
      categorical_features: [ 'sequence', 'variables', 'danger' ]
      numerical_features: [ ]
      datetime: 'timestamp'
      target: 'target'
      prediction: 'prediction'
    data_format:
      header: true
      separator: ','
      date_column: 'timestamp'
    monitors:
      - data_drift
      - classification_performance
      - cat_target_drift
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
  source: s3
  bucket: datakflow
